blank_issues_enabled: true
contact_links:
  - name: Reticulum manual
    url: https://reticulum.network/manual/index.html
    about: Normative protocol and API documentation for the Reticulum Network Stack.
